### ISSUE TITLE
Don't declare periodic table of elements in vocabulary

### ISSUE THREAD

**Issue by msporny** [transmute-industries/traceability-vocab#1]
We should not declare periodic table elements in a traceability vocabulary. DARPA did this work in 2003:

http://explore.dublincore.net/learning_resource/periodic-table-in-owl/

There is also the Ontology of Chemical Elements, which is current and put together by biometical ontologists:

https://bioportal.bioontology.org/ontologies/OCE/?p=summary

At the very least, we really should involve chemists, physicists, etc. to determine how this work should be done... but not to the degree that this turns into a multi-year effort. Taking the two ontologies above and doing a simpler one that merges the common terms expressed in each might work as well -- but could be a significant undertaking on its own.

**Comment by OR13** [comment]
> We should declare periodic table elements in a traceability vocabulary. DARPA did this work in 2003:

I assume you mean don't?

**Comment by msporny** [comment]
> I assume you mean don't?

Doh, yes, I meant "we should **not** declare periodic table elements in a traceability vocabulary."

I just changed the original issue text to fix that.

**Comment by OR13** [comment]
@msporny I would prefer to define them, even if its just a pass through definition as we have done for PostalAddress....

https://transmute-industries.github.io/traceability-vocab/#postal-address-0 ->
https://www.gs1.org/voc/PostalAddress -> https://schema.org/PostalAddress

The problem is I have not found a single example that is helpful to "pass through too"... I am, and forever will be... against term definitions that do not resolve (schema.org is 500 right now.... lol)

**Comment by msporny** [comment]
> The problem is I have not found a single example that is helpful to "pass through too"... 

Yes, that tends to be a consistent problem with these "scientist-created" vocabularies... extremely complex because they need the complexity. :)

> I am, and forever will be... against term definitions that do not resolve (schema.org is 500 right not.... lol)

What!? You must be mistaken... Google is never down. *stares at Error: Server Error* :P 

On a somewhat related note, GS1's vocabulary documents look really good... 

https://www.gs1.org/voc/PostalAddress

We should steal the layout... perhaps move away from ReSpec (which was always meant to be a temporary solution). /cc @philarcher

**Comment by philarcher** [comment]
> > The problem is I have not found a single example that is helpful to "pass through too"...
> 
> Yes, that tends to be a consistent problem with these "scientist-created" vocabularies... extremely complex because they need the complexity. :)
> 
> > I am, and forever will be... against term definitions that do not resolve (schema.org is 500 right not.... lol)
> 
> What!? You must be mistaken... Google is never down. _stares at Error: Server Error_ :P
> 
> On a somewhat related note, GS1's vocabulary documents look really good...
> 
> https://www.gs1.org/voc/PostalAddress
> 
> We should steal the layout... perhaps move away from ReSpec (which was always meant to be a temporary solution). /cc @philarcher

I wish I could claim credit for the GS1 Web Voc layout, but that accolade goes to https://github.com/orgs/gs1/people/mgh128. I know it's driven by PHP which is why we can't use it directly in the Web Voc's own GH repo at https://github.com/gs1/WebVoc

**Comment by msporny** [comment]
/me Github crawls https://github.com/mgh128/ ends up at another helpful thing for this vocab -- https://github.com/datasets/unece-units-of-measure

**Comment by msporny** [comment]
While we have your attention @philarcher -- From an RDF vocabulary perspective, what does GS1 do for Units of Measure?

**Comment by OR13** [comment]
@mgh128 thanks!

**Comment by OR13** [comment]
@msporny  https://www.gs1.org/voc/SizeDetails -> https://www.gs1.org/voc/QuantitativeValue

**Comment by mgh128** [comment]
@msporny Hi Manu - GS1 usually uses UN ECE Rec 20 units of measure throughout its standards, even though they're not yet very Linked Data friendly.  While QUDT 2.0  was taking a while to appear and because we're adding sensor data to our GS1 EPCIS 2.0 standard for supply chain traceability data, we've prepared this unit converter for the Rec 20 unit of measure codes ( https://github.com/gs1/UnitConverterUNECERec20 )  to deal with the situation where one organisation might record some sensor data using one unit of measure (e.g. 'FAH' for degrees Fahrenheit) and another organisation sends a query asking for event data where the temperature threshold exceeded a value expressed in a different but interconvertible unit (e.g. 'CEL' for degrees Celsius).   Online demo page at https://gs1.github.io/UnitConverterUNECERec20/
If you have any questions or suggestions on that, please let me know

Within the GS1 Web vocabulary at https://www.gs1.org/voc  the property  https://www.gs1.org/voc/unitCode within the class https://www.gs1.org/voc/QuantitativeValue expects a UN ECE Rec 20 unit code string.

**Comment by mgh128** [comment]
> I wish I could claim credit for the GS1 Web Voc layout, but that accolade goes to https://github.com/orgs/gs1/people/mgh128. I know it's driven by PHP which is why we can't use it directly in the Web Voc's own GH repo at https://github.com/gs1/WebVoc

I've started preparing an updated of the online documentation tool for the GS1 Web vocabulary.   The  new version is all client-side written in Vue.js, still data-driven by the JSON-LD dataset for the GS1 Web vocabulary.   Unfortunately a few other things are higher up my to-do list for GS1 - but when it's done, the plan is that we'll put the new version of the tool as a GitHub.io page for https://github.com/gs1/WebVoc  - and at that point, you're welcome to 'steal' / modify a copy for other purposes.  I'll try to write it in a way that it's reusable.    The current tool at https://www.gs1.org/voc is a rather unwieldy mix of server-side PHP code and client-side JavaScript code from a few years ago, to ensure that it worked with  /   without JavaScript enabled in the browser or search engine crawler.

**Comment by msporny** [comment]
> The new version is all client-side written in Vue.js, still data-driven by the JSON-LD dataset for the GS1 Web vocabulary. ...I'll try to write it in a way that it's reusable. 

Brilliant! This would be perfect and is aligned with a development environment that much of us are familiar with... if we time this right, we could get multiple folks hacking on the code at the same time. There is a cohort of funded companies in the US that would need that sort of tool in the next 6-9 months. If we do this right, we should be able to generalize it for all Linked Data vocabulary publishing at W3C (and GS1?!). In any case, getting ahead of ourselves... looking forward to anything you can share sooner rather than later... we'd be interested in contributing to the code base (as we're going to end up writing something very similar out of necessity).

Well done on GS1 SmartSearch vocabulary btw... it's a shining example of a Linked Data vocabulary. Very much a fan. :)

**Comment by OR13** [comment]
amazing how hard it is to find a stable defintion for "atomic Number" or "atomic symbol".... I have spent hours on https://lov.linkeddata.es/dataset/lov

so far, 

- http://dbpedia.org/ontology/atomicNumber
- http://dbpedia.org/ontology/casNumber

are the best things I have found.

**Comment by msporny** [comment]
> are the best things I have found.

@kidehen and @TallTed -- how stable is dbpedia.org? What's the governance model around it? If we started using terms in it for international standards, what do you expect the arguments against it would be?

**Comment by OR13** [comment]
seems like chebi, may actually work...

- http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/

of course all the URLs don't go anyhere, and elements are identified via CHEBI IDs....

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:155866

**Comment by mgh128** [comment]
I found this:

http://qudt.org/vocab/quantitykind/AtomicNumber

**Comment by OR13** [comment]
thanks! 

I am considering generalizing beyond "elements" to molecular structures... https://blogs.ch.cam.ac.uk/pmr/2009/04/05/cas-and-inchi-who-can-assign-identifiers/#:~:text=CAS%20states%20its%20numbers%20refer,as%20more%20than%20one%20substance.

**Comment by OR13** [comment]
also useful... https://pubchem.ncbi.nlm.nih.gov/

**Comment by OR13** [comment]
https://chem.nlm.nih.gov/chemidplus/rn/1333-74-0
https://www.webelements.com/hydrogen/

**Comment by msporny** [comment]
> http://qudt.org/vocab/quantitykind/AtomicNumber

Hey @HolgerKnublauch, how stable do you think the qudt.org site is? If we used it as the basis for a global standard vocabulary, would you have any misgivings? Could we expect anyone to object based on how the site is operated from a governance perspective?

**Comment by mgh128** [comment]
Within GS1 EPCIS 2.0 we're referencing InChi key values to identify
chemical substances in sensor data.

More about InChi key at :
https://en.m.wikipedia.org/wiki/International_Chemical_Identifier

**Comment by msporny** [comment]
> Within GS1 EPCIS 2.0 we're referencing InChi key values to identify chemical substances in sensor data.

Could you give an example of this when doing something like an rdf:type? My guess is:

```
<_bn:1> <inchi:element> "H" .
```

and I was hoping for:

```
<_bn:1> <rdf:type> <inchi:H> .
```

**Comment by OR13** [comment]
@msporny 

https://pubchem.ncbi.nlm.nih.gov/#query=InChI%3D1S%2FTi

```
 <chebi:formula rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ti</chebi:formula>
        <chebi:inchi rdf:datatype="http://www.w3.org/2001/XMLSchema#string">InChI=1S/Ti</chebi:inchi>
        <chebi:inchikey rdf:datatype="http://www.w3.org/2001/XMLSchema#string">RTAQQCXQSZGOHL-UHFFFAOYSA-N</chebi:inchikey>
```
see also: 
http://registry2.it.csiro.au/def/op?_format=jsonld&_view=with_metadata

**Comment by OR13** [comment]
https://schema.org/Substance

**Comment by msporny** [comment]
> https://pubchem.ncbi.nlm.nih.gov/#query=InChI%3D1S%2FTi

Hrm... all strings... no rdf:types in sight for things on the periodic table. I'm not a chemist by any stretch of the imagination, so I'm probably missing something obvious. chebi/inchi/qudt do seem like the leading contenders for the use case.

In any case, my goal with this issue was to avoid work done elsewhere and I think @OR13 is on the trail so will disengage at this point leaving him to brave this particular rabbit hole with the rest cc'd on this thread... hope it isn't too deep. :)

**Comment by OR13** [comment]
no plz halp!

lol, i think this is good enough for now: https://transmute-industries.github.io/traceability-vocab/#substance

schema.org + chebi => any substance that can be expressed with inchikey

**Comment by mgh128** [comment]
At
https://github.com/gs1/EPCIS/blob/master/JSON/WithSensorData/SensorDataExample8.json
you can see one of our draft examples using InChi Key (see line 91).

However, we probably should change the value to instead use something like
https://identifiers.org/inchikey:RYYVLZVUVIJVGH-UHFFFAOYSA-N

so that instead of us writing "chemicalSubstance":"
urn:epcglobal:cbv:inchikey:CZMRCDWAGMRECN-UGDNZRGBSA-N"

we'd write "chemicalSubstance" : "
https://identifiers.org/inchikey:CZMRCDWAGMRECN-UGDNZRGBSA-N"

I'll recommend that we make that change to our drafts - will mention it in
our GS1 EPCIS call next week - and by e-mail to the chapter editors / core
team before then.

( We are trying to move away from URNs (URIs that Resolve Nowhere) and drag
our GS1 standards into the 21st century - but it's taking time to win
everyone over! )







On Sat, Oct 3, 2020 at 6:04 PM Manu Sporny <notifications@github.com> wrote:
>
> Within GS1 EPCIS 2.0 we're referencing InChi key values to identify
chemical substances in sensor data.
>
> Could you give an example of this when doing something like an rdf:type?
My guess is:

**Comment by OR13** [comment]
links moved: https://github.com/gs1/EPCIS/blob/master/JSON/WithSensorData/SensorDataExample8.jsonld#L27

https://identifiers.org/inchikey:CZMRCDWAGMRECN-UGDNZRGBSA-N

http://www.chemspider.com/Chemical-Structure.5768.html?rid=c3d9f0ff-4a93-45a3-81e2-262442e665c6

very cool @mgh128 !

**Comment by OR13** [comment]
https://registry.identifiers.org/registry/did :)

**Comment by HolgerKnublauch** [comment]
Manu, I have notified Ralph Hodgson who maintains qudt. If you don't hear from him here, please follow up directly with him.

**Comment by msporny** [comment]
@HolgerKnublauch wrote:
> Manu, I have notified Ralph Hodgson who maintains qudt. If you don't hear from him here, please follow up directly with him.

Awesome, thank you Holger!

**Comment by OR13** [comment]
please move discussion to the W3C CCG.
